---
name: vault

variables:
- name: ca
  type: certificate
  options:
    is_ca: true
    alternative_names:
    - 127.0.0.1
- name: tls
  type: certificate
  options:
    ca: ca
    alternative_names:
    - 127.0.0.1
- name: concourse
  type: certificate
  options:
    ca: ca
    alternative_names:
    - 127.0.0.1
    extended_key_usage:
    - client_auth


stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

releases:
- name: vault
  version: latest

instance_groups:
- name: vault
  instances: 1
  vm_type: default
  azs: [z1]
  stemcell: trusty
  networks: [{name: default, static_ips: [10.244.0.2]}]
  jobs:
  - name: vault
    release: vault
    properties:
      tls: ((tls))
      concourse: ((concourse))

update:
  canaries: 0
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
